### ISSUE TITLE
PermissionGrant: Introduce Support for flashing Gapps

### ISSUE THREAD

**Issue by 0xBADEAFFE** [AOSPA/android_frameworks_base-uvite#13]
I think this should be merged into AOSPA for OpenGapps: https://github.com/TeamExodus/frameworks_base/commit/9c36be651e83fb039a262682839bd920b033007a

**Comment by TheCrazyLex** [comment]
We have a gerrit at gerrit.aospa.co
Please submit there.

**Comment by 0xBADEAFFE** [comment]
@TheCrazyLex Sadly I have not the time to get familiar with gerrit. Any chance to get it submited anyway?

**Comment by TheCrazyLex** [comment]
PA works fine without the patch, so it is not necessary here.

**Comment by 0xBADEAFFE** [comment]
OK, I'll close the issue.
