### ISSUE TITLE
Malformed assertion in DisplayManagerServiceTest

### ISSUE THREAD

**Issue by amaembo** [AOSPA/android_frameworks_base-uvite#21]
Hello!

Just spotted a malformed assertion here:
https://github.com/AOSPA/android_frameworks_base/blob/1d8f323e61fa7e6078a7f5db4f38f7bc23787172/services/tests/servicestests/src/com/android/server/display/DisplayManagerServiceTest.java#L466

```java
Exception thrown = null;
try {
    displayManager.validateBrightnessConfiguration(config);
} catch (IllegalArgumentException e) {
    thrown = e;
}
assertNotNull("Building too dark a brightness configuration must throw an exception");
```

The assertion checks that the textual string is not-null which is always so. The fact that the exception was thrown is not checked at all. Likely, it was intended to write

```java
assertNotNull("Building too dark a brightness configuration must throw an exception", thrown);
```

**Comment by xboxfanj** [comment]
Hi @amaembo, Thank you for noticing this and sharing it with us.  However, this is upstream code from the Android Open Source Project and PA is not actually using these test cases, so it does not make sense to deviate from upstream for our purposes.  However, AOSP may be interested in it and you can try submitting to https://android-review.googlesource.com/dashboard/self for Google's engineers to review.
