### ISSUE TITLE
app2sd is not present

### ISSUE THREAD

**Issue by elliot-huffman** [AOSPA/android_frameworks_base-uvite#8]
Native app2sd is not present on Samsung Galaxy S III (d2lte/d2spr). Supposedly this is due to improper mounting of internal/external storage.

PA 4.45 stable (Android 4.4.4)

Thanks for looking into the issue :)

**Comment by Anu6is** [comment]
The Galaxy SIII is not managed in this Git repo

Legacy devices are maintained at -> https://github.com/AOSPA-legacy

**Comment by elliot-huffman** [comment]
hmmm... Issues are not supported there. Are you a dev got that branch?

**Comment by Anu6is** [comment]
No, I not a dev on the legacy branch. Didn't realize issues are not supported there.

**Comment by elliot-huffman** [comment]
@Anu6is If you could, could you please notify the admin(s) about this issue?

**Comment by kaluoshi** [comment]
@elliot-labs Didn't know issues were disabled there, someone did it but i wasn't aware. Just re-enabled issues on frameworks and settings.

**Comment by elliot-huffman** [comment]
I just checked and the issues for d2lte is are disabled...
https://github.com/AOSPA-legacy/android_device_samsung_d2lte

Thanks for your interest!

**Comment by kaluoshi** [comment]
Done, seams disabled everywhere :\ I guess someone decided to silence reports :(

**Comment by elliot-huffman** [comment]
thx!

On Fri, Jan 2, 2015 at 8:28 PM, Carlo Savignano notifications@github.com
wrote:

> Done, seams disabled everywhere :\ I guess someone decided to silence
> reports :(
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AOSPA/android_frameworks_base/issues/8#issuecomment-68578341
> .

## 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by elliot-huffman** [comment]
I have reposted the issue onto the d2lte repo.

Thanks for your help!

On Fri, Jan 2, 2015 at 9:01 PM, Elliot Huffman thelich2@gmail.com wrote:

> thx!
> 
> On Fri, Jan 2, 2015 at 8:28 PM, Carlo Savignano notifications@github.com
> wrote:
> 
> > Done, seams disabled everywhere :\ I guess someone decided to silence
> > reports :(
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/AOSPA/android_frameworks_base/issues/8#issuecomment-68578341
> > .
> 
> ## 
> 
> Elliot
> 
> DISCLAIMER:
> This e-mail is for the intended recipient(s) only
> 
> If you have received it by mistake please let me know by reply and then
> delete it from your system; access, disclosure, copying, distribution or
> reliance on any of it by anyone else is prohibited.
> 
> If you as intended recipient have received this e-mail incorrectly, please
> notify the sender (via e-mail) immediately.

## 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.
